apiVersion: v1
kind: ConfigMap
metadata:
  name: oc-devspaces-pythonapp
  labels:
    app: oc-devspaces-pythonapp
    app.kubernetes.io/name: oc-devspaces-pythonapp
data:
  APP_MESSAGE: "Hello World!"
